# The different Materials to look for within the mine structure.
locale: "en_US"

settings:
  taxes: true
  menu: true
  storage: "YAML" # Or SQLite

materials:
  spawn-point: SPONGE
  mine-corner: POWERED_RAIL
  sell-npc: WHITE_WOOL
  upgrade: OBSIDIAN
  quarry: SHULKER_BOX

mine:
  first-join-creation: true
  is-closed-by-default: true
  distance: 150
  y-level: 50
  tp-delay: 5
  reset-cooldown: 15
  configuration:
    should-create-wall-gap: true
    walls-go-up: false
    gap: 1

onlyReplaceAir: true
borderUpgrade: true
defaultClosed: true

mineTypes:
  default:
    file: defaultmine.schem
    reset:
      time: 5
      percentage: 15
    expand: 1
    upgradeCost: 1.0
    hooks:
      oraxen: false
      itemsAdder: false
    materials:
      cobblestone: 100.0
      oraxen_your_block_id: 0.5
      itemsadder_your_block_id: 0.5
    default-flags:
      block-break: true
      upc-enchants: true
    full-flags:
      block-place: false
    prices:
      COBBLESTONE: 1.0